
import Header from './components/Header'
import './globals.css'
import Auth from "./components/Auth"
import { Inter } from 'next/font/google'
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs'
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const DynamicHeader = dynamic(() => import('./components/Header'), { ssr: false });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
      <ClerkProvider>
      <SignedOut>
      <Auth/>
        <SignInButton />
        
        </SignedOut>
      <SignedIn>
           {/* <Header /> */}
           <DynamicHeader />
          {children}
          {/* <UserButton /> */}
        </SignedIn>
      
          </ClerkProvider>
        
      </body>
    </html>
  );
}